/*El query devuelve un número aleatorio del 0 al 9  para cada fila del 1 al 10 */

SELECT ROWNUM ORDEN ,LOGIN_END FROM (
SELECT LOGIN_END, RDM FROM (                                        
SELECT 0 LOGIN_END ,DBMS_RANDOM.VALUE(0,10)RDM FROM dual UNION
SELECT 1 LOGIN_END ,DBMS_RANDOM.VALUE(0,10)RDM FROM dual UNION
SELECT 2 LOGIN_END ,DBMS_RANDOM.VALUE(0,10)RDM FROM dual UNION
SELECT 3 LOGIN_END ,DBMS_RANDOM.VALUE(0,10)RDM FROM dual UNION
SELECT 4 LOGIN_END ,DBMS_RANDOM.VALUE(0,10)RDM FROM dual UNION
SELECT 5 LOGIN_END ,DBMS_RANDOM.VALUE(0,10)RDM FROM dual UNION
SELECT 6 LOGIN_END ,DBMS_RANDOM.VALUE(0,10)RDM FROM dual UNION
SELECT 7 LOGIN_END ,DBMS_RANDOM.VALUE(0,10)RDM FROM dual UNION
SELECT 8 LOGIN_END ,DBMS_RANDOM.VALUE(0,10)RDM FROM dual UNION
SELECT 9 LOGIN_END ,DBMS_RANDOM.VALUE(0,10)RDM FROM dual )
ORDER BY 2);




